export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS'

export const LOAD_WORKSPACE_SUCCESS = 'LOAD_WORKSPACE_SUCCESS'
export const LOAD_WORKSPACE_REQUEST = 'LOAD_WORKSPACE_REQUEST'

export const LOAD_PROJECTS_REQUEST = 'LOAD_PROJECTS_REQUEST'
export const LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS'
export const SELECT_PROJECT = 'SELECT_PROJECT'

export const SOCKET_CONNECT = 'CONNECT_SOCKET'
export const SOCKET_CONNECTED = 'SOCKET_CONNECTED'
export const SOCKET_CONNECTING = 'SOCKET_CONNECTING'
export const CONNECT_SOCKET_FAILURE = 'CONNECT_SOCKET_FAILURE'

export const CHANNEL_CONNECTED = 'CHANNEL_CONNECTED'
export const CHANNEL_CONNECTING = 'CHANNEL_CONNECTING'

export const LOAD_USER_NOTIFICATIONS = 'LOAD_USER_NOTIFICATIONS'

export const LOAD_ISSUES_REQUEST = 'LOAD_ISSUES_REQUEST'
export const LOAD_ISSUES_SUCCESS = 'LOAD_ISSUES_SUCCESS'
