export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS'

export const LOAD_WORKSPACE_SUCCESS = 'LOAD_WORKSPACE_SUCCESS'
export const LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS'
